name: Beta

on:
  push:
    branches: [ 'beta/**' ]

jobs:
  Authorization:
    name: "Beta : Authorization"
    runs-on: ubuntu-latest
    env:
      working-directory: ./NugetPackagesSourceCode/Sherweb.Apis.Authorization

    steps:
    - uses: actions/checkout@master
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.working-directory}}
    - name: Publish NuGet
      run: dotnet nuget push Sherweb.Apis.Authorization.*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: ${{env.working-directory}}/bin/Release

  Distributor:
    name: "Beta : Distributor"
    runs-on: ubuntu-latest
    env:
      working-directory: ./NugetPackagesSourceCode/Sherweb.Apis.Distributor

    steps:
    - uses: actions/checkout@master
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.working-directory}}
    - name: Publish NuGet
      run: dotnet nuget push Sherweb.Apis.Distributor.*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: ${{env.working-directory}}/bin/Release

  SampleCode:
    name: "Beta : SampleCode"
    runs-on: ubuntu-latest
    env:
      working-directory: ./SampleCode

    steps:
    - uses: actions/checkout@master
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.working-directory}}

  ServiceProvider:
    name: "Beta : ServiceProvider"
    runs-on: ubuntu-latest
    env:
      working-directory: ./NugetPackagesSourceCode/Sherweb.Apis.ServiceProvider

    steps:
    - uses: actions/checkout@master
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.working-directory}}
    - name: Publish NuGet
      run: dotnet nuget push Sherweb.Apis.ServiceProvider.*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: ${{env.working-directory}}/bin/Release